-- phase: expand
-- OpenVibe.Network on PostgreSQL (ADR-035, roadmap WS-X2): the tables as they were on SQLite (converted by openvibe-sdk
-- tools/asyncify/sqlite-schema-to-pg: text COLLATE "C" compares like SQLite, integers are bigint, identities keep their ids),
-- then the openvibe-publishing stores and the openvibe-sdk inbox and outbox. Generated once on 2026-09-29; never edited after it runs.
-- SQLite's text timestamps and date functions (openvibe-sdk tools/asyncify SQLITE_DATE_FUNCTIONS).
CREATE FUNCTION ov_ts(t text) RETURNS timestamp LANGUAGE plpgsql STABLE AS $$
BEGIN
    IF t IS NULL THEN RETURN NULL; END IF;
    IF t = 'now' THEN RETURN statement_timestamp() AT TIME ZONE 'UTC'; END IF;
    IF t ~ '\d\d:\d\d(:\d\d(\.\d+)?)?\s*(Z|[+-]\d\d(:?\d\d)?)$' THEN RETURN t::timestamptz AT TIME ZONE 'UTC'; END IF;
    RETURN t::timestamp;
EXCEPTION WHEN others THEN RETURN NULL;
END $$;
CREATE FUNCTION ov_now() RETURNS text LANGUAGE sql STABLE AS $$ SELECT to_char(statement_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS') $$;
CREATE FUNCTION ov_now_iso() RETURNS text LANGUAGE sql STABLE AS $$ SELECT to_char(statement_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') $$;
CREATE FUNCTION ov_now_iso(modifier text) RETURNS text LANGUAGE sql STABLE AS $$ SELECT to_char((statement_timestamp() AT TIME ZONE 'UTC') + modifier::interval, 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') $$;
CREATE FUNCTION datetime(t text, modifier text DEFAULT NULL) RETURNS text LANGUAGE plpgsql STABLE AS $$
DECLARE ts timestamp := ov_ts(t);
BEGIN
    IF ts IS NULL THEN RETURN NULL; END IF;
    IF modifier IS NOT NULL THEN ts := ts + modifier::interval; END IF;
    RETURN to_char(ts, 'YYYY-MM-DD HH24:MI:SS');
EXCEPTION WHEN others THEN RETURN NULL;
END $$;
CREATE FUNCTION julianday(t text) RETURNS double precision LANGUAGE sql STABLE AS $$ SELECT extract(epoch FROM ov_ts(t))::double precision / 86400.0 + 2440587.5 $$;

CREATE TABLE users (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username text COLLATE "C" NOT NULL,
    email text COLLATE "C" UNIQUE,
    password_hash text COLLATE "C" NOT NULL,
    display_name text COLLATE "C",
    avatar_url text COLLATE "C",
    bio text COLLATE "C" DEFAULT '',
    role text COLLATE "C" DEFAULT 'user' CHECK(role IN ('user','streamer','global_mod','admin')),
    profile_color text COLLATE "C" DEFAULT '#8b5cf6',
    is_banned bigint DEFAULT 0,
    ban_reason text COLLATE "C",
    token_valid_after text COLLATE "C" DEFAULT NULL,
    legacy_source text COLLATE "C",
    legacy_id bigint,
    created_at text COLLATE "C" DEFAULT ov_now(),
    updated_at text COLLATE "C" DEFAULT ov_now(),
    last_seen text COLLATE "C" DEFAULT ov_now(),
    is_anon bigint DEFAULT 0,
    anon_number bigint,
    name_effect text COLLATE "C",
    particle_effect text COLLATE "C",
    email_verified bigint DEFAULT 0,
    email_verified_at text COLLATE "C",
    email_bounced_at text COLLATE "C",
    email_bounce_reason text COLLATE "C",
    history_paused bigint DEFAULT 0,
    subject_id text COLLATE "C",
    profile_revision bigint NOT NULL DEFAULT 0,
    merged_into bigint,
    deleted_at text COLLATE "C"
);

CREATE TABLE oauth_clients (
    client_id text COLLATE "C" PRIMARY KEY,
    client_secret text COLLATE "C" NOT NULL,
    name text COLLATE "C" NOT NULL,
    redirect_uris text COLLATE "C" NOT NULL,
    is_first_party bigint DEFAULT 0,
    created_at text COLLATE "C" DEFAULT ov_now()
);

CREATE TABLE oauth_codes (
    code text COLLATE "C" PRIMARY KEY,
    client_id text COLLATE "C" NOT NULL,
    user_id bigint NOT NULL,
    redirect_uri text COLLATE "C" NOT NULL,
    scope text COLLATE "C" DEFAULT 'profile theme',
    expires_at text COLLATE "C" NOT NULL,
    used bigint DEFAULT 0,
    created_at text COLLATE "C" DEFAULT ov_now(),
    code_challenge text COLLATE "C",
    code_challenge_method text COLLATE "C",
    nonce text COLLATE "C",
    FOREIGN KEY (client_id) REFERENCES oauth_clients(client_id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE oauth_tokens (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    token text COLLATE "C" UNIQUE NOT NULL,
    client_id text COLLATE "C" NOT NULL,
    user_id bigint NOT NULL,
    scope text COLLATE "C" DEFAULT 'profile theme',
    expires_at text COLLATE "C" NOT NULL,
    revoked bigint DEFAULT 0,
    created_at text COLLATE "C" DEFAULT ov_now(),
    family_id text COLLATE "C",
    generation bigint NOT NULL DEFAULT 0,
    revoked_reason text COLLATE "C",
    revoked_at text COLLATE "C",
    FOREIGN KEY (client_id) REFERENCES oauth_clients(client_id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE user_preferences (
    user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    theme_id text COLLATE "C" DEFAULT 'vibe',
    custom_theme_variables text COLLATE "C",
    language text COLLATE "C" DEFAULT 'en',
    notifications_enabled bigint DEFAULT 1,
    updated_at text COLLATE "C" DEFAULT ov_now(),
    display_prefs text COLLATE "C",
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE themes (
    id text COLLATE "C" PRIMARY KEY,
    name text COLLATE "C" NOT NULL,
    slug text COLLATE "C" UNIQUE NOT NULL,
    author_id bigint,
    description text COLLATE "C" DEFAULT '',
    mode text COLLATE "C" DEFAULT 'dark' CHECK(mode IN ('dark','light')),
    variables text COLLATE "C" NOT NULL,
    preview_colors text COLLATE "C",
    is_builtin bigint DEFAULT 0,
    is_public bigint DEFAULT 1,
    downloads bigint DEFAULT 0,
    rating_sum bigint DEFAULT 0,
    rating_count bigint DEFAULT 0,
    tags text COLLATE "C" DEFAULT '[]',
    created_at text COLLATE "C" DEFAULT ov_now(),
    updated_at text COLLATE "C" DEFAULT ov_now(),
    FOREIGN KEY (author_id) REFERENCES users(id)
);

CREATE TABLE linked_accounts (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    service text COLLATE "C" NOT NULL,
    service_user_id text COLLATE "C" NOT NULL,
    linked_at text COLLATE "C" DEFAULT ov_now(),
    service_username text COLLATE "C",
    last_used_at text COLLATE "C",
    FOREIGN KEY (user_id) REFERENCES users(id),
    UNIQUE(service, service_user_id)
);

CREATE TABLE audit_log (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id bigint,
    action text COLLATE "C" NOT NULL,
    details text COLLATE "C",
    ip text COLLATE "C",
    created_at text COLLATE "C" DEFAULT ov_now()
);

CREATE TABLE ip_log (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id bigint,
    ip text COLLATE "C" NOT NULL,
    action text COLLATE "C" DEFAULT 'login',
    country text COLLATE "C",
    region text COLLATE "C",
    city text COLLATE "C",
    created_at text COLLATE "C" DEFAULT ov_now(),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE site_settings (
    key text COLLATE "C" PRIMARY KEY,
    value text COLLATE "C",
    type text COLLATE "C" DEFAULT 'string'
);

CREATE TABLE url_registry (
    key text COLLATE "C" PRIMARY KEY,
    label text COLLATE "C" NOT NULL,
    category text COLLATE "C" NOT NULL,
    service text COLLATE "C" NOT NULL,
    scope text COLLATE "C" NOT NULL,
    type text COLLATE "C" NOT NULL,
    value text COLLATE "C",
    description text COLLATE "C",
    updated_by bigint,
    updated_at text COLLATE "C" DEFAULT ov_now(),
    source text COLLATE "C" NOT NULL DEFAULT 'admin'
);

CREATE TABLE notifications (
    id text COLLATE "C" PRIMARY KEY,
    user_id bigint NOT NULL,
    type text COLLATE "C" NOT NULL,
    category text COLLATE "C" NOT NULL,
    priority text COLLATE "C" NOT NULL DEFAULT 'normal',
    title text COLLATE "C" NOT NULL,
    message text COLLATE "C",
    icon text COLLATE "C",
    sender_id bigint,
    sender_name text COLLATE "C",
    sender_avatar text COLLATE "C",
    service text COLLATE "C",
    url text COLLATE "C",
    rich_content text COLLATE "C",
    is_read bigint DEFAULT 0,
    is_dismissed bigint DEFAULT 0,
    is_emailed bigint DEFAULT 0,
    expires_at text COLLATE "C",
    created_at text COLLATE "C" DEFAULT ov_now(),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE notification_preferences (
    user_id bigint NOT NULL,
    category text COLLATE "C" NOT NULL,
    enabled bigint DEFAULT 1,
    sound bigint DEFAULT 1,
    toasts bigint DEFAULT 1,
    email bigint DEFAULT 0,
    PRIMARY KEY (user_id, category),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE email_delivery_log (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email_type text COLLATE "C" NOT NULL,
    recipient text COLLATE "C" NOT NULL,
    subject text COLLATE "C",
    status text COLLATE "C" NOT NULL CHECK(status IN ('sent', 'failed')),
    error_message text COLLATE "C",
    user_id bigint,
    notification_id text COLLATE "C",
    metadata text COLLATE "C",
    created_at text COLLATE "C" DEFAULT ov_now(),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (notification_id) REFERENCES notifications(id) ON DELETE SET NULL
);

CREATE TABLE password_reset_tokens (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    token_hash text COLLATE "C" UNIQUE NOT NULL,
    expires_at text COLLATE "C" NOT NULL,
    used_at text COLLATE "C",
    requested_ip text COLLATE "C",
    requested_user_agent text COLLATE "C",
    created_at text COLLATE "C" DEFAULT ov_now(),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE anon_users (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    anon_number bigint UNIQUE NOT NULL,
    fingerprint text COLLATE "C",
    session_token text COLLATE "C" UNIQUE NOT NULL,
    display_name text COLLATE "C",
    preferences text COLLATE "C" DEFAULT '{}',
    total_messages bigint DEFAULT 0,
    total_commands bigint DEFAULT 0,
    first_seen text COLLATE "C" DEFAULT ov_now(),
    last_seen text COLLATE "C" DEFAULT ov_now(),
    ip text COLLATE "C",
    subject_id text COLLATE "C"
);

CREATE TABLE user_sessions (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    session_token text COLLATE "C" UNIQUE NOT NULL,
    device_name text COLLATE "C",
    ip text COLLATE "C",
    user_agent text COLLATE "C",
    is_active bigint DEFAULT 1,
    last_used text COLLATE "C" DEFAULT ov_now(),
    created_at text COLLATE "C" DEFAULT ov_now(),
    expires_at text COLLATE "C" NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE user_effects (
    user_id bigint NOT NULL,
    effect_type text COLLATE "C" NOT NULL,
    effect_id text COLLATE "C" NOT NULL,
    is_active bigint DEFAULT 0,
    acquired_at text COLLATE "C" DEFAULT ov_now(),
    PRIMARY KEY (user_id, effect_type, effect_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE follows (
    follower_id bigint NOT NULL,
    followed_id bigint NOT NULL,
    created_at text COLLATE "C" DEFAULT ov_now(),
    PRIMARY KEY (follower_id, followed_id),
    FOREIGN KEY (follower_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (followed_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE wallets (
    user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    balance bigint NOT NULL DEFAULT 0,
    updated_at text COLLATE "C" DEFAULT ov_now(),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE coin_transactions (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    app_id text COLLATE "C",
    delta bigint NOT NULL,
    reason text COLLATE "C",
    ref text COLLATE "C",
    idempotency_key text COLLATE "C" UNIQUE,
    created_at text COLLATE "C" DEFAULT ov_now(),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE verification_keys (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    key text COLLATE "C" UNIQUE NOT NULL,
    target_username text COLLATE "C" NOT NULL,
    note text COLLATE "C" DEFAULT '',
    created_by bigint NOT NULL,
    used_by bigint,
    status text COLLATE "C" DEFAULT 'active' CHECK(status IN ('active', 'used', 'revoked')),
    created_at text COLLATE "C" DEFAULT ov_now(),
    used_at text COLLATE "C",
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (used_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE anon_ip_log (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    anon_id bigint NOT NULL,
    ip text COLLATE "C" NOT NULL,
    first_seen text COLLATE "C" DEFAULT ov_now(),
    last_seen text COLLATE "C" DEFAULT ov_now(),
    FOREIGN KEY (anon_id) REFERENCES anon_users(id) ON DELETE CASCADE,
    UNIQUE(anon_id, ip)
);

CREATE TABLE push_subscriptions (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    endpoint text COLLATE "C" NOT NULL UNIQUE,
    keys_p256dh text COLLATE "C" NOT NULL,
    keys_auth text COLLATE "C" NOT NULL,
    user_agent text COLLATE "C",
    created_at text COLLATE "C" DEFAULT ov_now(),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE email_verification_tokens (
    token_hash text COLLATE "C" PRIMARY KEY,
    user_id bigint NOT NULL,
    email text COLLATE "C" NOT NULL,
    created_at text COLLATE "C" DEFAULT ov_now(),
    expires_at text COLLATE "C" NOT NULL,
    used_at text COLLATE "C",
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE identity_legacy_map (
    source_system text COLLATE "C" NOT NULL,
    source_type text COLLATE "C" NOT NULL,
    source_id text COLLATE "C" NOT NULL,
    subject_id text COLLATE "C" NOT NULL,
    first_seen_at text COLLATE "C" DEFAULT ov_now(),
    verified_at text COLLATE "C",
    metadata text COLLATE "C",
    PRIMARY KEY (source_system, source_type, source_id)
);

CREATE TABLE principal_grants (
    client_id text COLLATE "C" NOT NULL,
    capability text COLLATE "C" NOT NULL,
    audience text COLLATE "C" NOT NULL,
    namespaces text COLLATE "C" NOT NULL DEFAULT '[]',
    granted_at text COLLATE "C" DEFAULT ov_now(),
    granted_by text COLLATE "C",
    revoked_at text COLLATE "C",
    expires_at text COLLATE "C",
    reason text COLLATE "C",
    revoked_by text COLLATE "C",
    PRIMARY KEY (client_id, capability, audience)
);

CREATE TABLE principal_usage (
    principal text COLLATE "C" NOT NULL,
    route text COLLATE "C" NOT NULL,
    capability text COLLATE "C" NOT NULL,
    auth text COLLATE "C" NOT NULL,
    allowed bigint NOT NULL,
    code text COLLATE "C" NOT NULL DEFAULT '',
    count bigint NOT NULL DEFAULT 0,
    first_at text COLLATE "C" DEFAULT ov_now(),
    last_at text COLLATE "C" DEFAULT ov_now(),
    PRIMARY KEY (principal, route, auth, allowed, code)
);

CREATE TABLE principal_grant_changes (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    client_id text COLLATE "C" NOT NULL,
    capability text COLLATE "C" NOT NULL,
    audience text COLLATE "C" NOT NULL,
    change text COLLATE "C" NOT NULL CHECK (change IN ('granted', 'updated', 'revoked', 'expired')),
    namespaces text COLLATE "C" NOT NULL DEFAULT '[]',
    expires_at text COLLATE "C",
    reason text COLLATE "C",
    actor text COLLATE "C",
    event_id text COLLATE "C",
    at text COLLATE "C" NOT NULL DEFAULT ov_now_iso()
);

CREATE TABLE user_modules (
    subject_id text COLLATE "C" NOT NULL,
    namespace text COLLATE "C" NOT NULL,
    version bigint NOT NULL,
    revision bigint NOT NULL DEFAULT 0,
    data text COLLATE "C" NOT NULL,
    updated_at text COLLATE "C" DEFAULT ov_now(),
    updated_by text COLLATE "C",
    PRIMARY KEY (subject_id, namespace)
);

CREATE TABLE user_module_revisions (
    subject_id text COLLATE "C" NOT NULL,
    namespace text COLLATE "C" NOT NULL,
    revision bigint NOT NULL,
    PRIMARY KEY (subject_id, namespace)
);

CREATE TABLE user_module_retirements (
    namespace text COLLATE "C" PRIMARY KEY,
    owner text COLLATE "C" NOT NULL,
    retired_seen_at bigint NOT NULL
);


CREATE TABLE dev_projects (
    id text COLLATE "C" PRIMARY KEY,
    owner_subject text COLLATE "C" NOT NULL,
    name text COLLATE "C" NOT NULL,
    environment_policy text COLLATE "C" NOT NULL DEFAULT 'sandbox' CHECK (environment_policy IN ('sandbox', 'sandbox+production')),
    allowance text COLLATE "C" NOT NULL DEFAULT '[]',
    created_at text COLLATE "C" NOT NULL,
    created_by text COLLATE "C" NOT NULL,
    archived_at text COLLATE "C",
    archived_by text COLLATE "C"
);

CREATE TABLE dev_project_members (
    project_id text COLLATE "C" NOT NULL REFERENCES dev_projects(id),
    subject_id text COLLATE "C" NOT NULL,
    role text COLLATE "C" NOT NULL CHECK (role IN ('owner', 'admin', 'developer', 'viewer')),
    added_at text COLLATE "C" NOT NULL,
    added_by text COLLATE "C" NOT NULL,
    PRIMARY KEY (project_id, subject_id)
);

CREATE TABLE dev_apps (
    id text COLLATE "C" PRIMARY KEY,
    project_id text COLLATE "C" NOT NULL REFERENCES dev_projects(id),
    name text COLLATE "C" NOT NULL,
    environment text COLLATE "C" NOT NULL CHECK (environment IN ('sandbox', 'production')),
    oauth_client_id text COLLATE "C" NOT NULL UNIQUE,
    client_type text COLLATE "C" NOT NULL CHECK (client_type IN ('confidential', 'public')),
    redirect_uris text COLLATE "C" NOT NULL DEFAULT '[]',
    created_at text COLLATE "C" NOT NULL,
    created_by text COLLATE "C" NOT NULL,
    revoked_at text COLLATE "C",
    revoked_by text COLLATE "C"
);

CREATE TABLE dev_credentials (
    id text COLLATE "C" PRIMARY KEY,
    app_id text COLLATE "C" NOT NULL REFERENCES dev_apps(id),
    secret_hash text COLLATE "C" NOT NULL UNIQUE,
    hint text COLLATE "C" NOT NULL,
    created_at text COLLATE "C" NOT NULL,
    created_by text COLLATE "C" NOT NULL,
    expires_at text COLLATE "C",
    revoked_at text COLLATE "C",
    revoked_by text COLLATE "C",
    last_used_at text COLLATE "C"
);

CREATE TABLE dev_grants (
    app_id text COLLATE "C" NOT NULL REFERENCES dev_apps(id),
    capability text COLLATE "C" NOT NULL,
    audience text COLLATE "C" NOT NULL,
    status text COLLATE "C" NOT NULL CHECK (status IN ('requested', 'approved', 'denied', 'revoked')),
    requested_by text COLLATE "C" NOT NULL,
    requested_at text COLLATE "C" NOT NULL,
    decided_by text COLLATE "C",
    decided_at text COLLATE "C",
    PRIMARY KEY (app_id, capability)
);

CREATE TABLE dev_quotas (
    project_id text COLLATE "C" NOT NULL REFERENCES dev_projects(id),
    capability text COLLATE "C" NOT NULL,
    limit_value bigint NOT NULL CHECK (limit_value >= 0),
    quota_window text COLLATE "C" NOT NULL CHECK (quota_window IN ('minute', 'hour', 'day', 'month', 'total')),
    unit text COLLATE "C" NOT NULL DEFAULT 'requests',
    updated_at text COLLATE "C" NOT NULL,
    updated_by text COLLATE "C" NOT NULL,
    PRIMARY KEY (project_id, capability)
);

CREATE TABLE dev_auth_codes (
    code_hash text COLLATE "C" PRIMARY KEY,
    app_id text COLLATE "C" NOT NULL REFERENCES dev_apps(id),
    user_subject text COLLATE "C" NOT NULL,
    redirect_uri text COLLATE "C" NOT NULL,
    scope text COLLATE "C" NOT NULL DEFAULT '',
    code_challenge text COLLATE "C" NOT NULL,
    expires_at text COLLATE "C" NOT NULL,
    used bigint NOT NULL DEFAULT 0
);

CREATE TABLE dev_audit (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    at text COLLATE "C" NOT NULL,
    project_id text COLLATE "C",
    actor text COLLATE "C" NOT NULL,
    action text COLLATE "C" NOT NULL,
    target text COLLATE "C",
    detail text COLLATE "C" NOT NULL DEFAULT '{}',
    request_id text COLLATE "C",
    event_type text COLLATE "C",
    event text COLLATE "C"
);

CREATE TABLE dev_usage_windows (
    project_id text COLLATE "C" NOT NULL,
    env text COLLATE "C" NOT NULL CHECK (env IN ('sandbox', 'production')),
    service text COLLATE "C" NOT NULL,
    capability text COLLATE "C" NOT NULL,
    dimension text COLLATE "C" NOT NULL DEFAULT '',
    unit text COLLATE "C" NOT NULL,
    window_start text COLLATE "C" NOT NULL,
    window_end text COLLATE "C" NOT NULL,
    quantity bigint NOT NULL,
    errors bigint NOT NULL,
    error_codes text COLLATE "C" NOT NULL DEFAULT '{}',
    revision bigint NOT NULL DEFAULT 1,
    event_id text COLLATE "C" NOT NULL,
    recorded_at text COLLATE "C" NOT NULL,
    PRIMARY KEY (project_id, env, service, capability, dimension, unit, window_start)
);

CREATE TABLE dev_usage_daily (
    project_id text COLLATE "C" NOT NULL,
    env text COLLATE "C" NOT NULL,
    service text COLLATE "C" NOT NULL,
    capability text COLLATE "C" NOT NULL,
    dimension text COLLATE "C" NOT NULL DEFAULT '',
    unit text COLLATE "C" NOT NULL,
    day text COLLATE "C" NOT NULL,
    quantity bigint NOT NULL DEFAULT 0,
    errors bigint NOT NULL DEFAULT 0,
    error_codes text COLLATE "C" NOT NULL DEFAULT '{}',
    updated_at text COLLATE "C" NOT NULL,
    PRIMARY KEY (project_id, env, service, capability, dimension, unit, day)
);

CREATE TABLE dev_usage_errors (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    project_id text COLLATE "C" NOT NULL,
    env text COLLATE "C" NOT NULL,
    service text COLLATE "C" NOT NULL,
    capability text COLLATE "C" NOT NULL,
    at text COLLATE "C" NOT NULL,
    code text COLLATE "C" NOT NULL,
    status bigint,
    trace_id text COLLATE "C",
    ref text COLLATE "C" NOT NULL DEFAULT '',
    event_id text COLLATE "C" NOT NULL
);

CREATE TABLE user_blocks (
    blocker_subject text COLLATE "C" NOT NULL,
    blocked_subject text COLLATE "C" NOT NULL,
    active bigint NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
    revision bigint NOT NULL DEFAULT 1 CHECK (revision >= 1),
    created_at text COLLATE "C" NOT NULL DEFAULT ov_now_iso(),
    updated_at text COLLATE "C" NOT NULL DEFAULT ov_now_iso(),
    PRIMARY KEY (blocker_subject, blocked_subject),
    CHECK (blocker_subject <> blocked_subject)
);

CREATE TABLE user_follows (
    follower_subject text COLLATE "C" NOT NULL,
    target_type text COLLATE "C" NOT NULL CHECK (target_type IN ('channel')),
    target_id text COLLATE "C" NOT NULL,
    active bigint NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
    notify_email bigint NOT NULL DEFAULT 1 CHECK (notify_email IN (0, 1)),
    notify_push bigint NOT NULL DEFAULT 1 CHECK (notify_push IN (0, 1)),
    revision bigint NOT NULL DEFAULT 1 CHECK (revision >= 1),
    source text COLLATE "C" NOT NULL DEFAULT 'network',
    created_at text COLLATE "C" NOT NULL DEFAULT ov_now_iso(),
    updated_at text COLLATE "C" NOT NULL DEFAULT ov_now_iso(),
    PRIMARY KEY (follower_subject, target_type, target_id),
    CHECK (follower_subject <> target_id)
);

CREATE TABLE follow_import_holds (
    source text COLLATE "C" NOT NULL,
    follower_ref text COLLATE "C" NOT NULL,
    target_ref text COLLATE "C" NOT NULL,
    reason text COLLATE "C" NOT NULL,
    seen_at text COLLATE "C" NOT NULL,
    PRIMARY KEY (source, follower_ref, target_ref)
);

CREATE TABLE status_incidents (
    id text COLLATE "C" PRIMARY KEY,
    kind text COLLATE "C" NOT NULL CHECK (kind IN ('incident', 'maintenance')),
    title text COLLATE "C" NOT NULL,
    severity text COLLATE "C" CHECK (severity IS NULL OR severity IN ('minor', 'major', 'critical')),
    state text COLLATE "C" NOT NULL,
    services text COLLATE "C" NOT NULL DEFAULT '[]',
    starts_at text COLLATE "C" NOT NULL,
    ends_at text COLLATE "C",
    created_by text COLLATE "C" NOT NULL,
    created_at text COLLATE "C" NOT NULL,
    updated_at text COLLATE "C" NOT NULL
);

CREATE TABLE status_incident_updates (
    incident_id text COLLATE "C" NOT NULL REFERENCES status_incidents(id),
    at text COLLATE "C" NOT NULL,
    state text COLLATE "C" NOT NULL,
    message text COLLATE "C" NOT NULL,
    author text COLLATE "C" NOT NULL
);

CREATE TABLE creator_streams (
    stream_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_subject text COLLATE "C" NOT NULL,
    title text COLLATE "C",
    category text COLLATE "C",
    started_at text COLLATE "C" NOT NULL,
    ended_at text COLLATE "C" NOT NULL,
    duration_seconds bigint NOT NULL DEFAULT 0,
    peak_viewers bigint,
    avg_viewers double precision,
    unique_chatters bigint,
    messages bigint,
    watch_minutes bigint,
    received_at text COLLATE "C" NOT NULL
);

CREATE TABLE platform_nodes (
    id text COLLATE "C" PRIMARY KEY,
    source text COLLATE "C" NOT NULL,
    doc text COLLATE "C" NOT NULL,
    status text COLLATE "C" NOT NULL,
    reported_at text COLLATE "C" NOT NULL
);

CREATE TABLE username_history (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    old_username text COLLATE "C" NOT NULL,
    new_username text COLLATE "C" NOT NULL,
    changed_by bigint,
    changed_at text COLLATE "C" DEFAULT ov_now()
);

CREATE TABLE user_profile_changes (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    changed text COLLATE "C" NOT NULL,
    at bigint NOT NULL
);

CREATE TABLE subject_aliases (
    alias_id text COLLATE "C" PRIMARY KEY,
    subject_id text COLLATE "C" NOT NULL,
    merge_id text COLLATE "C" NOT NULL,
    merged_at text COLLATE "C" NOT NULL,
    merged_by text COLLATE "C" NOT NULL
);

CREATE TABLE account_merges (
    id text COLLATE "C" PRIMARY KEY,
    from_subject text COLLATE "C" NOT NULL UNIQUE,
    into_subject text COLLATE "C" NOT NULL,
    from_user_id bigint NOT NULL,
    into_user_id bigint NOT NULL,
    initiated_by text COLLATE "C" NOT NULL CHECK (initiated_by IN ('person', 'staff')),
    actor_subject text COLLATE "C" NOT NULL,
    reason text COLLATE "C",
    moved text COLLATE "C" NOT NULL,
    pre_state text COLLATE "C",
    merged_at text COLLATE "C" NOT NULL,
    split_until text COLLATE "C" NOT NULL,
    reduced_at text COLLATE "C"
);

CREATE TABLE account_merge_intents (
    id text COLLATE "C" PRIMARY KEY,
    into_user_id bigint NOT NULL,
    created_at bigint NOT NULL,
    expires_at bigint NOT NULL,
    used_at bigint
);

CREATE TABLE account_exports (
    id text COLLATE "C" PRIMARY KEY,
    user_id bigint NOT NULL,
    subject text COLLATE "C" NOT NULL,
    status text COLLATE "C" NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'ready', 'partial', 'expired', 'failed')),
    expected text COLLATE "C" NOT NULL DEFAULT '[]',
    requested_at text COLLATE "C" NOT NULL,
    deadline text COLLATE "C" NOT NULL,
    ready_at text COLLATE "C",
    expires_at text COLLATE "C",
    size_bytes bigint,
    services text COLLATE "C",
    error text COLLATE "C"
);

CREATE TABLE account_export_parts (
    export_id text COLLATE "C" NOT NULL,
    service text COLLATE "C" NOT NULL,
    received_at text COLLATE "C" NOT NULL,
    files bigint NOT NULL,
    bytes bigint NOT NULL,
    body text COLLATE "C",
    PRIMARY KEY (export_id, service)
);

CREATE TABLE account_deletions (
    id text COLLATE "C" PRIMARY KEY,
    user_id bigint NOT NULL,
    subject text COLLATE "C" NOT NULL,
    status text COLLATE "C" NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'cancelled', 'deleted')),
    requested_at text COLLATE "C" NOT NULL,
    delete_after text COLLATE "C" NOT NULL,
    cancelled_at text COLLATE "C",
    cancelled_by text COLLATE "C",
    deleted_at text COLLATE "C",
    expected text COLLATE "C",
    erased text COLLATE "C"
);

CREATE TABLE account_deletion_confirmations (
    deletion_id text COLLATE "C" NOT NULL,
    service text COLLATE "C" NOT NULL,
    received_at text COLLATE "C" NOT NULL,
    completed_at text COLLATE "C" NOT NULL,
    erased text COLLATE "C" NOT NULL,
    retained text COLLATE "C" NOT NULL,
    PRIMARY KEY (deletion_id, service)
);

CREATE TABLE mod_principals (
    mod_id text COLLATE "C" PRIMARY KEY,
    owner text COLLATE "C" NOT NULL,
    runtime text COLLATE "C" NOT NULL,
    name text COLLATE "C",
    version text COLLATE "C",
    publisher text COLLATE "C",
    manifest text COLLATE "C" NOT NULL,
    status text COLLATE "C" NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'revoked')),
    revision bigint NOT NULL DEFAULT 1,
    created_at text COLLATE "C" NOT NULL,
    created_by text COLLATE "C",
    updated_at text COLLATE "C" NOT NULL,
    revoked_at text COLLATE "C",
    revoked_by text COLLATE "C"
);

CREATE TABLE mod_principal_grants (
    mod_id text COLLATE "C" NOT NULL,
    capability text COLLATE "C" NOT NULL,
    state text COLLATE "C" NOT NULL CHECK (state IN ('pending', 'approved', 'revoked')),
    changed_at text COLLATE "C" NOT NULL,
    changed_by text COLLATE "C",
    PRIMARY KEY (mod_id, capability)
);

CREATE TABLE stream_live_announcements (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    streamer_key text COLLATE "C" NOT NULL,
    stream_id text COLLATE "C",
    sent_at text COLLATE "C" DEFAULT ov_now()
);

CREATE TABLE operator_alerts (
    source text COLLATE "C" NOT NULL,
    fingerprint text COLLATE "C" NOT NULL,
    name text COLLATE "C" NOT NULL,
    severity text COLLATE "C" NOT NULL,
    summary text COLLATE "C" NOT NULL,
    description text COLLATE "C",
    service text COLLATE "C",
    state text COLLATE "C" NOT NULL CHECK (state IN ('firing', 'resolved')),
    started_at text COLLATE "C" NOT NULL,
    opened_at bigint NOT NULL,
    last_seen_at bigint NOT NULL,
    notified_at bigint,
    resolved_at bigint,
    notices text COLLATE "C",
    reopened bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (source, fingerprint)
);

CREATE TABLE tool_domains (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tool_id text COLLATE "C" NOT NULL,
    host text COLLATE "C" NOT NULL UNIQUE,
    role text COLLATE "C" NOT NULL DEFAULT 'alias' CHECK (role IN ('canonical', 'short', 'alias', 'mirror')),
    enabled bigint NOT NULL DEFAULT 1,
    note text COLLATE "C",
    created_by bigint,
    created_at text COLLATE "C" DEFAULT ov_now(),
    updated_at text COLLATE "C" DEFAULT ov_now()
);

CREATE TABLE user_history (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    service text COLLATE "C",
    sub text COLLATE "C",
    type text COLLATE "C" NOT NULL DEFAULT 'page',
    title text COLLATE "C" NOT NULL,
    url text COLLATE "C" NOT NULL,
    icon text COLLATE "C",
    meta text COLLATE "C",
    hits bigint NOT NULL DEFAULT 1,
    created_at text COLLATE "C" DEFAULT ov_now(),
    updated_at text COLLATE "C" DEFAULT ov_now(),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE frame_cache (
    key text COLLATE "C" PRIMARY KEY,
    value text COLLATE "C" NOT NULL,
    updated_at text COLLATE "C" DEFAULT ov_now()
);

CREATE TABLE frame_hits (
    day text COLLATE "C" NOT NULL,
    host text COLLATE "C" NOT NULL,
    hits bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (day, host)
);

CREATE UNIQUE INDEX idx_users_username_lower ON users(lower(username));
CREATE INDEX idx_notif_user_read ON notifications(user_id, is_read, created_at DESC);
CREATE INDEX idx_notif_user_cat ON notifications(user_id, category);
CREATE INDEX idx_notif_expires ON notifications(expires_at) WHERE expires_at IS NOT NULL;
CREATE INDEX idx_email_delivery_created ON email_delivery_log(created_at DESC);
CREATE INDEX idx_email_delivery_status ON email_delivery_log(status, created_at DESC);
CREATE INDEX idx_email_delivery_type ON email_delivery_log(email_type, created_at DESC);
CREATE INDEX idx_password_reset_user ON password_reset_tokens(user_id, used_at, expires_at);
CREATE INDEX idx_password_reset_expires ON password_reset_tokens(expires_at);
CREATE INDEX idx_sessions_user ON user_sessions(user_id, is_active);
CREATE INDEX idx_sessions_token ON user_sessions(session_token);
CREATE INDEX idx_coin_tx_user ON coin_transactions(user_id, created_at DESC);
CREATE INDEX idx_coin_tx_app ON coin_transactions(app_id, created_at DESC);
CREATE INDEX idx_vkeys_key ON verification_keys(key);
CREATE INDEX idx_vkeys_target ON verification_keys(target_username);
CREATE INDEX idx_vkeys_status ON verification_keys(status);
CREATE INDEX idx_anon_ip_log_ip ON anon_ip_log(ip);
CREATE INDEX idx_anon_ip_log_anon ON anon_ip_log(anon_id);
CREATE INDEX idx_push_sub_user ON push_subscriptions(user_id);
CREATE INDEX idx_push_sub_endpoint ON push_subscriptions(endpoint);
CREATE INDEX idx_oauth_tokens_family ON oauth_tokens(family_id);
CREATE INDEX idx_email_verify_user ON email_verification_tokens(user_id, created_at DESC);
CREATE UNIQUE INDEX idx_linked_user_service ON linked_accounts(user_id, service);
CREATE INDEX idx_identity_legacy_subject ON identity_legacy_map(subject_id);
CREATE UNIQUE INDEX idx_users_subject_id ON users(subject_id);
CREATE UNIQUE INDEX idx_anon_users_subject_id ON anon_users(subject_id);
CREATE INDEX idx_grant_changes_client ON principal_grant_changes(client_id, id);
CREATE INDEX idx_dev_projects_owner ON dev_projects(owner_subject);
CREATE INDEX idx_dev_members_subject ON dev_project_members(subject_id);
CREATE INDEX idx_dev_apps_project ON dev_apps(project_id);
CREATE INDEX idx_dev_credentials_app ON dev_credentials(app_id);
CREATE INDEX idx_dev_audit_project ON dev_audit(project_id, id);
CREATE INDEX idx_dev_usage_windows_when ON dev_usage_windows(window_start);
CREATE INDEX idx_dev_usage_windows_project ON dev_usage_windows(project_id, recorded_at);
CREATE INDEX idx_dev_usage_daily_day ON dev_usage_daily(project_id, day);
CREATE UNIQUE INDEX idx_dev_usage_errors_once ON dev_usage_errors(project_id, env, service, capability, at, code, ref);
CREATE INDEX idx_dev_usage_errors_recent ON dev_usage_errors(project_id, at);
CREATE INDEX idx_user_blocks_blocked ON user_blocks(blocked_subject, active);
CREATE INDEX idx_user_follows_target ON user_follows(target_type, target_id, active, created_at);
CREATE INDEX idx_status_incident_updates ON status_incident_updates(incident_id, at);
CREATE INDEX idx_creator_streams_creator ON creator_streams(creator_subject, started_at);
CREATE INDEX idx_username_history_old ON username_history(lower(old_username));
CREATE INDEX idx_username_history_user ON username_history(user_id);
CREATE INDEX idx_user_profile_changes_user ON user_profile_changes(user_id);
CREATE INDEX idx_subject_aliases_subject ON subject_aliases(subject_id);
CREATE INDEX idx_account_exports_user ON account_exports(user_id, requested_at);
CREATE UNIQUE INDEX idx_account_deletions_open ON account_deletions(user_id) WHERE status = 'scheduled';
CREATE INDEX idx_sla_key ON stream_live_announcements(streamer_key, sent_at DESC);
CREATE INDEX idx_tool_domains_tool ON tool_domains(tool_id, role, enabled);
CREATE INDEX idx_user_history_user_time ON user_history(user_id, updated_at DESC);
CREATE INDEX idx_user_history_user_url ON user_history(user_id, url);

CREATE FUNCTION user_modules_guard_users_delete() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF OLD.subject_id IS NOT NULL AND EXISTS (SELECT 1 FROM user_modules WHERE subject_id = OLD.subject_id) THEN RAISE EXCEPTION 'user_modules rows remain for this subject: call modules.onSubjectRemoved or onSubjectMerged first'; END IF; RETURN OLD; END $$;
CREATE TRIGGER user_modules_guard_users_delete BEFORE DELETE ON users FOR EACH ROW EXECUTE FUNCTION user_modules_guard_users_delete();

CREATE FUNCTION user_modules_guard_users_rekey() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF OLD.subject_id IS NOT NULL AND NEW.subject_id IS DISTINCT FROM OLD.subject_id AND EXISTS (SELECT 1 FROM user_modules WHERE subject_id = OLD.subject_id) THEN RAISE EXCEPTION 'user_modules rows remain for this subject: call modules.onSubjectMerged first'; END IF; RETURN NEW; END $$;
CREATE TRIGGER user_modules_guard_users_rekey BEFORE UPDATE OF subject_id ON users FOR EACH ROW EXECUTE FUNCTION user_modules_guard_users_rekey();

CREATE FUNCTION user_modules_guard_anon_users_delete() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF OLD.subject_id IS NOT NULL AND EXISTS (SELECT 1 FROM user_modules WHERE subject_id = OLD.subject_id) THEN RAISE EXCEPTION 'user_modules rows remain for this subject: call modules.onSubjectRemoved or onSubjectMerged first'; END IF; RETURN OLD; END $$;
CREATE TRIGGER user_modules_guard_anon_users_delete BEFORE DELETE ON anon_users FOR EACH ROW EXECUTE FUNCTION user_modules_guard_anon_users_delete();

CREATE FUNCTION user_modules_guard_anon_users_rekey() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF OLD.subject_id IS NOT NULL AND NEW.subject_id IS DISTINCT FROM OLD.subject_id AND EXISTS (SELECT 1 FROM user_modules WHERE subject_id = OLD.subject_id) THEN RAISE EXCEPTION 'user_modules rows remain for this subject: call modules.onSubjectMerged first'; END IF; RETURN NEW; END $$;
CREATE TRIGGER user_modules_guard_anon_users_rekey BEFORE UPDATE OF subject_id ON anon_users FOR EACH ROW EXECUTE FUNCTION user_modules_guard_anon_users_rekey();

CREATE FUNCTION dev_audit_append_only_update() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'dev_audit is append-only'; RETURN NEW; END $$;
CREATE TRIGGER dev_audit_append_only_update BEFORE UPDATE ON dev_audit FOR EACH ROW EXECUTE FUNCTION dev_audit_append_only_update();

CREATE FUNCTION dev_audit_append_only_delete() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'dev_audit is append-only'; RETURN OLD; END $$;
CREATE TRIGGER dev_audit_append_only_delete BEFORE DELETE ON dev_audit FOR EACH ROW EXECUTE FUNCTION dev_audit_append_only_delete();

CREATE FUNCTION users_profile_changed() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF COALESCE(NEW.is_anon, 0) = 0 AND (OLD.username IS DISTINCT FROM NEW.username OR OLD.display_name IS DISTINCT FROM NEW.display_name OR OLD.avatar_url IS DISTINCT FROM NEW.avatar_url OR OLD.profile_color IS DISTINCT FROM NEW.profile_color OR OLD.role IS DISTINCT FROM NEW.role OR OLD.is_banned IS DISTINCT FROM NEW.is_banned) THEN INSERT INTO user_profile_changes (user_id, changed, at) VALUES (NEW.id, trim((CASE WHEN OLD.username IS DISTINCT FROM NEW.username THEN 'username ' ELSE '' END) || (CASE WHEN OLD.display_name IS DISTINCT FROM NEW.display_name THEN 'display_name ' ELSE '' END) || (CASE WHEN OLD.avatar_url IS DISTINCT FROM NEW.avatar_url THEN 'avatar_url ' ELSE '' END) || (CASE WHEN OLD.profile_color IS DISTINCT FROM NEW.profile_color THEN 'profile_color ' ELSE '' END) || (CASE WHEN OLD.role IS DISTINCT FROM NEW.role THEN 'role ' ELSE '' END) || (CASE WHEN OLD.is_banned IS DISTINCT FROM NEW.is_banned THEN 'banned ' ELSE '' END)), (extract(epoch FROM statement_timestamp()) * 1000)::bigint); END IF; RETURN NULL; END $$;
CREATE TRIGGER users_profile_changed AFTER UPDATE OF username, display_name, avatar_url, profile_color, role, is_banned ON users FOR EACH ROW EXECUTE FUNCTION users_profile_changed();

CREATE FUNCTION users_profile_created() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF COALESCE(NEW.is_anon, 0) = 0 THEN INSERT INTO user_profile_changes (user_id, changed, at) VALUES (NEW.id, 'created', (extract(epoch FROM statement_timestamp()) * 1000)::bigint); END IF; RETURN NULL; END $$;
CREATE TRIGGER users_profile_created AFTER INSERT ON users FOR EACH ROW EXECUTE FUNCTION users_profile_created();

-- The rows the SQLite boot seeded (built-in themes, default settings, the first-party OAuth clients with their
-- per-install generated secrets, the platform's default principal grants) are not frozen here: server/db/database.js
-- seeds them idempotently at boot, exactly as it did on SQLite, so each install generates its own client secrets.

-- openvibe-sdk/events inbox: one receipt per (consumer, event) handled
CREATE TABLE IF NOT EXISTS network_event_inbox (
    consumer     text NOT NULL,
    event_id     text NOT NULL,
    processed_at bigint NOT NULL,
    PRIMARY KEY (consumer, event_id)
);

-- openvibe-sdk/events PostgreSQL outbox
CREATE TABLE IF NOT EXISTS network_event_outbox (
    id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    event_id        text NOT NULL UNIQUE,
    envelope        jsonb NOT NULL,
    traceparent     text,
    created_at      bigint NOT NULL,
    attempts        integer NOT NULL DEFAULT 0,
    next_attempt_at bigint NOT NULL DEFAULT 0,
    sent_at         bigint,
    seq             bigint,
    rejected_at     bigint,
    last_error      text
);
CREATE INDEX IF NOT EXISTS network_event_outbox_due ON network_event_outbox (next_attempt_at, id) WHERE sent_at IS NULL AND rejected_at IS NULL;
CREATE INDEX IF NOT EXISTS network_event_outbox_sent ON network_event_outbox (sent_at) WHERE sent_at IS NOT NULL;
