-- phase: expand
-- plan T2. Two tables the code created lazily (never at boot, so 0001_initial.sql missed them),
-- and the insertion-order `seq` identity for the tables whose code ordered by SQLite's implicit rowid.
-- PostgreSQL has no rowid; `seq` is a per-row identity, monotonic in insertion order, unique.

CREATE TABLE admin_rate_limits (
    user_id bigint NOT NULL,
    action  text   NOT NULL,
    last_at bigint NOT NULL,
    PRIMARY KEY (user_id, action)
);

CREATE TABLE moderation_audit (
    id             bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    event_id       text NOT NULL UNIQUE,
    service        text NOT NULL,
    action         text NOT NULL,
    actor_subject  text,
    target_type    text,
    target_id      text,
    target_subject text,
    scope          text,
    reason         text,
    details        text NOT NULL DEFAULT '{}',
    occurred_at    text NOT NULL,
    recorded_at    text NOT NULL DEFAULT ov_now_iso(),
    seq            bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE
);
CREATE INDEX idx_modaudit_when ON moderation_audit(occurred_at);
CREATE INDEX idx_modaudit_service ON moderation_audit(service, id);
CREATE INDEX idx_modaudit_actor ON moderation_audit(actor_subject, id);

ALTER TABLE linked_accounts          ADD COLUMN seq bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE;
ALTER TABLE user_sessions            ADD COLUMN seq bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE;
ALTER TABLE oauth_tokens             ADD COLUMN seq bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE;
ALTER TABLE oauth_codes              ADD COLUMN seq bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE;
ALTER TABLE notifications            ADD COLUMN seq bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE;
ALTER TABLE push_subscriptions       ADD COLUMN seq bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE;
ALTER TABLE notification_preferences ADD COLUMN seq bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE;
ALTER TABLE user_preferences         ADD COLUMN seq bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE;
ALTER TABLE user_effects             ADD COLUMN seq bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE;
ALTER TABLE username_history         ADD COLUMN seq bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE;
ALTER TABLE coin_transactions        ADD COLUMN seq bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE;
ALTER TABLE user_follows             ADD COLUMN seq bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE;
ALTER TABLE user_blocks              ADD COLUMN seq bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE;
ALTER TABLE dev_projects             ADD COLUMN seq bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE;
ALTER TABLE dev_project_members      ADD COLUMN seq bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE;
ALTER TABLE status_incident_updates  ADD COLUMN seq bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE;
