-- phase: expand
-- plan T2. Identity columns are GENERATED BY DEFAULT, not ALWAYS: an INSERT may name an id, the way the
-- SQLite PRIMARY KEYs it replaces allowed (the tests seed explicit ids; the one-time import writes the
-- source ids). Production never names one, so the sequence still owns new rows. Applied to every identity
-- column the earlier migrations created, whatever their table.

DO $$
DECLARE r record;
BEGIN
    FOR r IN
        SELECT c.table_name, c.column_name
        FROM information_schema.columns c
        WHERE c.table_schema = current_schema()
          AND c.is_identity = 'YES'
          AND c.identity_generation = 'ALWAYS'
    LOOP
        EXECUTE format('ALTER TABLE %I ALTER COLUMN %I SET GENERATED BY DEFAULT', r.table_name, r.column_name);
    END LOOP;
END $$;
